name: Deploy PROD (Angular → S3/CloudFront)

on:
  push:
    branches: [ "ui-release" ]
    paths:
      - 'hl-web/**'
      - '.github/workflows/deploy-ui-release.yml'
  workflow_dispatch: {}

# Set once so every run step occurs in the subfolder
defaults:
  run:
    working-directory: hl-web

env:
  NODE_VERSION: '20'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: hl-web/package-lock.json  # 👈 point to subfolder lockfile


      - name: Build Angular
        working-directory: hl-web                         # 👈 run inside subfolder
        run: |
          npm ci
          npm run build -- --configuration=production
      
      - name: Detect build output path
        id: detect
        shell: bash
        working-directory: hl-web
        run: |
          OUT=$(node -e "const f=require('./angular.json'); function find(o){ if(o&&typeof o==='object'){ if('outputPath'in o) return o.outputPath; for(const k of Object.keys(o)){ const r=find(o[k]); if(r) return r; } } }; const p=find(f); if(!p){ process.exit(1);} console.log(p);")
          echo "BUILD_DIR=$OUT" >> "$GITHUB_OUTPUT"

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Sync to S3
        run: |
          BUILD_DIR="${{ steps.detect.outputs.BUILD_DIR }}"
          if [ -z "$BUILD_DIR" ]; then BUILD_DIR="dist"; fi
          echo "Deploying from: hl-web/$BUILD_DIR"
          aws s3 sync "hl-web/$BUILD_DIR" "s3://${{ vars.S3_BUCKET }}" --delete --only-show-errors

      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id ${{ vars.CF_DIST_ID }} --paths "/*"
